.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. cducoin_qt test_cducoin_qt
clean: FORCE
	$(MAKE) -C .. cducoin_qt_clean test_cducoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_cducoin_qt_check
cducoin-qt cducoin-qt.exe: FORCE
	 $(MAKE) -C .. cducoin_qt
apk: FORCE
	$(MAKE) -C .. cducoin_qt_apk
